main_eps_small_graph: main_eps_small_graph.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_eps_small_graph main_eps_small_graph.cpp SFMT.c -L/usr/local/lib/

main_eps_small_graph_w_pruning: main_eps_small_graph_w_pruning.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_eps_small_graph_w_pruning main_eps_small_graph_w_pruning.cpp SFMT.c -L/usr/local/lib/

main_eps_small_graph_wo_pruning: main_eps_small_graph_wo_pruning.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_eps_small_graph_wo_pruning main_eps_small_graph_wo_pruning.cpp SFMT.c -L/usr/local/lib/

main_eps_large_graph: main_eps_large_graph.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_eps_large_graph main_eps_large_graph.cpp SFMT.c -L/usr/local/lib/

main_eps_large_graph_w_pruning: main_eps_large_graph_w_pruning.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_eps_large_graph_w_pruning main_eps_large_graph_w_pruning.cpp SFMT.c -L/usr/local/lib/

main_eps_large_graph_wo_pruning: main_eps_large_graph_wo_pruning.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_eps_large_graph_wo_pruning main_eps_large_graph_wo_pruning.cpp SFMT.c -L/usr/local/lib/

getidx: getidx.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o getidx getidx.cpp SFMT.c -L/usr/local/lib/ -ltcmalloc
	
main_small_graph_topk: main_small_graph_topk.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_small_graph_topk main_small_graph_topk.cpp SFMT.c

main_small_graph_topk_basic: main_small_graph_topk_basic.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_small_graph_topk_basic main_small_graph_topk_basic.cpp SFMT.c
	
main_eps_small_graph_self_loop: main_eps_small_graph_self_loop.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_eps_small_graph_self_loop main_eps_small_graph_self_loop.cpp SFMT.c -L/usr/local/lib/

main_thres_small_graph: main_thres_small_graph.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_thres_small_graph main_thres_small_graph.cpp SFMT.c -L/usr/local/lib/

main_topk_small_graph: main_topk_small_graph.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_topk_small_graph main_topk_small_graph.cpp SFMT.c
	
main_thres_large_graph: main_thres_large_graph.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_thres_large_graph main_thres_large_graph.cpp SFMT.c -L/usr/local/lib/

main_thres_small_graph_fig7: main_thres_small_graph_fig7.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_thres_small_graph_fig7 main_thres_small_graph_fig7.cpp SFMT.c -L/usr/local/lib/

main_thres_small_graph_fig8: main_thres_small_graph_fig8.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_thres_small_graph_fig8 main_thres_small_graph_fig8.cpp SFMT.c -L/usr/local/lib/


main_thres_large_graph_fig8: main_thres_large_graph_fig8.cpp SFMT.c
	g++ -march=core2  -std=c++11 -DSFMT_MEXP=607 -I SFMT-src-1.4.1/ -O3 -o main_thres_large_graph_fig8 main_thres_large_graph_fig8.cpp SFMT.c -L/usr/local/lib/

clean: 
	rm main_threshold main_topk getidx main_eps_small_graph
