
eps_metrics_small_graph: eps_metrics_small_graph.cpp
	g++ -std=c++11 -o eps_metrics_small_graph eps_metrics_small_graph.cpp 

eps_metrics_large_graph: eps_metrics_large_graph.cpp
	g++ -std=c++11 -o eps_metrics_large_graph eps_metrics_large_graph.cpp 

eps_metrics_small_graph_thres: eps_metrics_small_graph_thres.cpp
	g++ -std=c++11 -o eps_metrics_small_graph_thres eps_metrics_small_graph_thres.cpp 

eps_metrics_large_graph_thres: eps_metrics_large_graph_thres.cpp
	g++ -std=c++11 -o eps_metrics_large_graph_thres eps_metrics_large_graph_thres.cpp 

eps_metrics_small_graph_UISim: eps_metrics_small_graph_UISim.cpp
	g++ -std=c++11 -o eps_metrics_small_graph_UISim eps_metrics_small_graph_UISim.cpp

eps_metrics_large_graph_UISim: eps_metrics_large_graph_UISim.cpp
	g++ -std=c++11 -o eps_metrics_large_graph_UISim eps_metrics_large_graph_UISim.cpp 

