
eps_metrics_small_graph_rate: eps_metrics_small_graph_rate.cpp
	g++ -std=c++11 -o eps_metrics_small_graph_rate eps_metrics_small_graph_rate.cpp 

gene_topk_small_graph: gene_topk_small_graph.cpp
	g++ -std=c++11 -o gene_topk_small_graph gene_topk_small_graph.cpp 

gene_topk_large_graph: gene_topk_large_graph.cpp
	g++ -std=c++11 -o gene_topk_large_graph gene_topk_large_graph.cpp 

check_topk_graph_UISim: check_topk_graph_UISim.cpp
	g++ -std=c++11 -o check_topk_graph_UISim check_topk_graph_UISim.cpp 

