thres_metrics_small_graph: thres_metrics_small_graph.cpp
	g++ -std=c++11 -o thres_metrics_small_graph thres_metrics_small_graph.cpp

thres_metrics_large_graph: thres_metrics_large_graph.cpp
	g++ -std=c++11 -o thres_metrics_large_graph thres_metrics_large_graph.cpp